<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="karima-hp" failures="1" tests="7" name="code_1stfeb.Assignement" time="47.267" errors="0" timestamp="26 Jun 2023 01:06:57 GMT" skipped="0">
  <testcase classname="code_1stfeb.Assignement" name="logoutFunctionality" time="8.131"/>
  <testcase classname="code_1stfeb.Assignement" name="clickOnMyAccount" time="4.937">
    <failure message="As per the assignment" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: As per the assignment
at org.testng.Assert.fail(Assert.java:96)
at code_1stfeb.Assignement.clickOnMyAccount(Assignement.java:25)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- clickOnMyAccount -->
  <testcase classname="code_1stfeb.Assignement" name="logoutFunctionality" time="6.784"/>
  <testcase classname="code_1stfeb.Assignement" name="logoutFunctionality" time="7.007"/>
  <testcase classname="code_1stfeb.Assignement" name="loginFunctionality" time="6.549"/>
  <testcase classname="code_1stfeb.Assignement" name="logoutFunctionality" time="6.898"/>
  <testcase classname="code_1stfeb.Assignement" name="logoutFunctionality" time="6.961"/>
</testsuite> <!-- code_1stfeb.Assignement -->
